name: Deploy Azure Resources

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Deploy Bicep
      uses: azure/CLI@v1
      with:
        inlineScript: |
          az deployment group create \
            --resource-group BCSAI2024-DEVOPS-STUDENTS-B-DEV \
            --template-file main.bicep \
            --parameters @parameters.json
            --parameters containerRegistryUsername=${{ secrets.ACR_USERNAME }} \
                           containerRegistryPassword=${{ secrets.ACR_PASSWORD }} \